### ISSUE TITLE
SRM Analyser

### ISSUE THREAD

**Issue by leoferrao** [OTGApps/BeerJudge#5]
Camera is not working. The app opens, but the camera doesn't show an image, it is blank and when you click on the photo button the app closes.

**Comment by markrickert** [comment]
Thanks for the report... It is working on my iPhone 6. What device do you have where it's not working?

**Comment by leoferrao** [comment]
Hi,

I'm using the iphone 5 C with the latest IOS.

When I first bought the app a year ago it was working fine.

Leonardo 

Date: Sun, 4 Jan 2015 11:53:22 -0800

**Comment by kellerbrauer** [comment]
I'm using 5s with the latest iOS and mine is not working either. In fact, the app crashes when I try to use it.

**Comment by markrickert** [comment]
OK, this should be fixed in the next version, pending apple review.
