### ISSUE TITLE
iPhone 6S Plus issue opening off flavored 

### ISSUE THREAD

**Issue by thomasbarnett12** [OTGApps/BeerJudge#6]
Hi,

I just downloaded the Beer Judge app on my iPhone 6S Plus and when I try to click in the off flavors tab it shuts the app down.  

Not sure what to do.  This feature is why u downloaded the app. 

Any help would be much appreciated.

Thanks!

**Comment by aswensen** [comment]
I have the same issue on my iPhone 6 (not the 6s) running iOS 9.0.2. As above, any help would be greatly appreciated. 

Cheers!

**Comment by markrickert** [comment]
Hey guys. Sorry about this. I'm going to take a look at it tomorrow and see if I can come up with a solution. IOS 9 changed a LOT of things :(

**Comment by markrickert** [comment]
OK, this should be fixed in the next version, pending apple review.
